### ISSUE TITLE
pyls language server for Python unable to start

### ISSUE THREAD

**Issue by samarth-math** [lgeiger/ide-python#101]
Error: spawn pyls ENOENT

whereis pyls
pyls: /usr/local/bin/pyls

this is in the PATH

Let me know if I can attach anymore output

**Comment by lgeiger** [comment]
Looks like `pyls` is not in the PATH or Atom can't find it for some other reason.

Does running `pyls --help` from the command line work?

You can add `/usr/local/bin/pyls` directly to the "Python Language Server Path" settings in the `ide-python` settings to fix this problem.

**Comment by samarth-math** [comment]
Hey, so pyls was in the path actually,

but I think I figured the issue, I had installed ATOM from the repository, which might not be the latest version.

I uninstalled and installed from the official website, and this issue went away, I'll close this now.

Thanks for your quick response, and this editor looks amazing.
