### ISSUE TITLE
rope completion hangs whenever async/await is involved

### ISSUE THREAD

**Issue by extraymond** [lgeiger/ide-python#103]
Hi! 

When have rope completion enable(though I never understand it's usage XD), it become really slow whenever async/await keyword is involved.

Take the following code as example:

```
...
await some_async_function(variable)
...
```

After typing variable in the function signature field, the linter will emit errors saying:

undefined name v
undefined name va
undefined name var
undefined name vari
undefined name varia
undefined name variab
undefined name variabl

Like it's formatting once at a time. Guessing some nested loop is racing to lint and format the code that is hard to be done in async programming. I'm just into async programming so hope someone who knows python more deeply can help me bisect this bug.

Thx

**Comment by lgeiger** [comment]
Looks like rope doesn't support async/await: https://github.com/python-rope/rope/issues/215

Does it work when only using Jedi? `python-language-server@0.18.0` should've shipped support for async/await using Jedi.

**Comment by extraymond** [comment]
@lgeiger  Yes! Disable rope and let jedi take control works fine!

**Comment by lgeiger** [comment]
@extraymond Glad it works with Jedi. I'm closing this issue since it is a Rope bug.

**Comment by extraymond** [comment]
Thx
