### ISSUE TITLE
Fixed issues lingering in diagnostics until new issues found

### ISSUE THREAD

**Issue by matthewwardrop** [lgeiger/ide-python#105]
Greetings all!

Not sure if this is a known issue or not, but I cannot find it in the issue tracker.

Recently (since several weeks ago), issues identified by python-language-server show up quickly in the Atom interface, but fixed issue never disappear until another issue is found (in which case the issues are quickly replaced with the new ones).

I haven't been able to find the versions that worked previously for me, but I am presently on Atom 1.26.1, python-language-server 0.18, atom-ide-ui 0.11.1, ide-python 0.9.2 on MacOS.

I've tried disabling all other packages, and reinstalling all of these packages, to no avail.

**Comment by lgeiger** [comment]
Could you provide a code example or specific steps to reproduce this?
Is this happening only with a specific `pyls` plugin?

I just checked and cannot reproduce this with a simple toy example:
![kapture 2018-04-30 at 19 53 45](https://user-images.githubusercontent.com/13285808/39442128-837282dc-4cb0-11e8-8b2d-4d094ef3f1f4.gif)

**Comment by matthewwardrop** [comment]
Hmmm... I deleted some cache directories in the project folder (`.tox`, `.pytest`, ...) and now it works again. I'll follow up with a new issue if this issue returns and I can reproduce it better.

Thanks for your quick response!

**Comment by lgeiger** [comment]
Glad it works now. Feel free to reopen, if the problem returns.

**Comment by kbrose** [comment]
FWIW I encounter this a lot if I save (ctrl s) quickly right after fixing an issue. The marker won't go away until I type some stuff and wait ~half a second _without saving_.

**Comment by lgeiger** [comment]
@kbrose I experienced this issue with older versions of the language server too but am unable to reproduce this with the latest version. Are you also running on Atom 1.26.1, python-language-server 0.18, atom-ide-ui 0.11.1 and ide-python 0.9.2?
