### ISSUE TITLE
pyls don't work

### ISSUE THREAD

**Issue by benbenji** [lgeiger/ide-python#107]
Hello,
I encountered some problems on ubuntu as if my pyls was not set up correctly.The auto-completion is not work as follow:
![problem](https://user-images.githubusercontent.com/2499988/39609044-753859a6-4f78-11e8-99d8-6d813869af76.jpg)

When I run pyls,there is a warning:
![pyls](https://user-images.githubusercontent.com/2499988/39608873-3542187e-4f77-11e8-8c8b-1f1571474681.jpg)
I change my pyls's path in python-ide
![pylssetting](https://user-images.githubusercontent.com/2499988/39609076-b5bba708-4f78-11e8-8b09-ca8e99a0600d.jpg)
my unbuntu is 14.04 python 2.76,this is my first time to use atom-ide and ide-python, I think they are very cool! Is there any way to get the debug info when ide-python runs so that I can give you more detail information about my problem ,thank you!

**Comment by lgeiger** [comment]
Checkout the release notes of [version 1.0](https://github.com/lgeiger/ide-python/releases/tag/v1.0.0)
