### ISSUE TITLE
Extra newline showing in the docs in the auto-completion window

### ISSUE THREAD

**Issue by CyberMango** [lgeiger/ide-python#109]
Just a minor unwanted behavior i spotted:
In the auto-completion window, where it shows the docs of the function it suggests to complete, the function's signature and its doc are  both shown with an extra newline. Its useless and takes up more space from the window.

with "ide-python" 's completion:
[![python_ide_extra_line.png](https://s7.postimg.cc/d632a2f8b/python_ide_extra_line.png)](https://postimg.cc/image/3ljfn6pw7/)

and just for reference, with "autocomplete-python" 's completion:
[![python_ide_no_extra_line.png](https://s7.postimg.cc/4qdhsdwvv/python_ide_no_extra_line.png)](https://postimg.cc/image/x38ziuilz/)

Personalty I think the latter is the desired behavior. 
I hope you agree.

**Comment by lgeiger** [comment]
This will hopefully be fixed by the language server in https://github.com/palantir/python-language-server/pull/348

Closing in favor of #95
