### ISSUE TITLE
Outline View not showing Class methods

### ISSUE THREAD

**Issue by Kilo59** [lgeiger/ide-python#11]
My Outline Tab is showing my imported modules and classes but not their methods.
Both classes in the screenshot are being defined in this file.

![image](https://user-images.githubusercontent.com/13108583/30485339-145a07fc-99fb-11e7-98df-65c5ef777037.png)

Outline for a different script (with no Class definitions in it) **is** showing all functions and references just fine.
The datetime class is being imported, it's not being defined in this script.

![image](https://user-images.githubusercontent.com/13108583/30486101-84b90fc8-99fd-11e7-929b-e08f3416d0ec.png)

Apologies if this is the expected behavior or  I'm missing some basic setting somewhere.

**Version:** 
```
1.21.0-beta0
```

**Packages:**
```
ask-stack@2.2.0
atom-ide-ui@0.3.3
busy-signal@1.4.3
file-icons@2.1.11
fonts@3.0.3
highlight-selected@0.13.1
ide-python@0.1.1
intentions@1.1.5
linter-flake8@2.2.1
linter-ui-default@1.6.9
minimap@4.29.6
minimap-find-and-replace@4.5.2
minimap-git-diff@4.3.1
minimap-highlight-selected@4.6.1
minimap-linter@2.0.2
python-autopep8@0.1.3
todo-show@2.0.0
```

**Comment by lgeiger** [comment]
I actually don't know if this is expected behavior of [`pyls`](https://github.com/palantir/python-language-server) or if it's a bug in [`atom-ide-ui`](https://github.com/facebook-atom/atom-ide-ui) 😄

**Comment by lgeiger** [comment]
I made a PR to `pyls` for this: https://github.com/palantir/python-language-server/pull/140

I hope it gets merged soon, so we can make this behavior configurable.

**Comment by dpwrussell** [comment]
I think you resolved that this was a `pyls` problem as it seems to work fine in Java in `atom-ide-ui`, so I guess it's not in that.

Would your PR also address the flattening of the structure in general? The above example has all those variables, but I think that really only top-level ones should be shown (and those nested in classes once that works).

**Comment by lgeiger** [comment]
Once https://github.com/palantir/python-language-server/pull/175 is merged, well have a correctly structured outline view.
