### ISSUE TITLE
Error installing Python-IDE

### ISSUE THREAD

**Issue by vdbarmar** [lgeiger/ide-python#110]
I want to install the Python-IDE but still getting this error

![image](https://user-images.githubusercontent.com/39258973/39984773-850a02fa-5719-11e8-8534-748b439f1847.png)

**Comment by kbrose** [comment]
Did you follow the instructions in the error message? Do you have `pyls` installed?

If you're on windows, you can try `where pyls` in the command prompt to determine if you have it installed. If you're on a UNIX machine you can try `which pyls` instead.

**Comment by Yimitis** [comment]
How to install python language server in windows?

**Comment by lgeiger** [comment]
Checkout the release notes of [version 1.0](https://github.com/lgeiger/ide-python/releases/tag/v1.0.0)
