### ISSUE TITLE
Unable to start the Python language server.

### ISSUE THREAD

**Issue by Yimitis** [lgeiger/ide-python#116]
This can occur if you do not have Python installed or if it is not in your path.

Make sure to install pyls by running:

pip install 'python-language-server[all]'

-----------------
THis is the error i get and i dont know how to handle .
I have installed python and im on windows so i cant run the command that it tells me to do...
Also what path does it want me to include and where???

**Comment by lgeiger** [comment]
Have you run: `pip install 'python-language-server[all]'` from the command line?

**Comment by lgeiger** [comment]
Here's how you can open the command prompt in windows: https://www.computerhope.com/issues/chusedos.htm

There you are supposed to enter and execute the command from the error message.

**Comment by Yimitis** [comment]
You actually need to run: pip install python-language-server[all] 
in promt
It works fine now. 
Is there supposed to be a runner too and or is it just showing warnings?

**Comment by lgeiger** [comment]
Glad it works now.

> Is there supposed to be a runner too and or is it just showing warnings?

Could you elaborate?

**Comment by benhadad** [comment]
He probably means when you type in 

python - m pip install 'python-language-server[all]' 
it failes with  ERROR: Invalid requirement: ''python-language-server[all]'

It succeeds when you remove the ' , like ->python - m pip install  python-language-server[all]

**Comment by felloz** [comment]
Im getting this error:
```
ERROR: Failed building wheel for ujson
```

Complete Error:
```
Building wheels for collected packages: ujson
  Building wheel for ujson (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\lserrano\appdata\local\programs\python\python37-32\python.exe' 'c:\users\lserrano\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\lserrano\AppData\Local\Temp\tmpxjzq45sl'
       cwd: C:\Users\lserrano\AppData\Local\Temp\pip-install-vo513mly\ujson
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for ujson
Failed to build ujson
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly
```

**Comment by philipnye** [comment]
@lgeiger Would you accept a pull request that removes the quote marks mentioned in @benhadad's comment? I come back to this package periodically, get the message that I need to I need to install `pylsp` then hit the error that Ben mentions when I try to install it. Every time it takes me 15 minutes of Googling before I find this GitHub issue and am reminded that I need to run the install command without single quotes.
