### ISSUE TITLE
How do I supress a specific pyflakes warning from showing up in the Diagnostics tab for a specific file/line only?

### ISSUE THREAD

**Issue by bradwood** [lgeiger/ide-python#118]
I've tried

`# pyflakes: noqa`
`# noqa`

no joy.

Thanks

**Comment by lgeiger** [comment]
Only specific errors are allowed to be ignored via `  # noqa` using `pycodestyle`.
Checkout http://pycodestyle.pycqa.org/en/latest/intro.html#error-codes

If I recall correctly `pyflakes` doesn't allow to ignore errors via `  # noqa` .
