### ISSUE TITLE
pipenv support

### ISSUE THREAD

**Issue by lucacorti** [lgeiger/ide-python#123]
I'm experiencing the same issue as #119. My project is using `pipenv` to manage dependencies so everything lives in its separated venv, including pyls as a deve dependency. Is this kind of setup supported at all?

I'd expect the python interpreter and dependencies from the virtualenv to be picked up automatically by `ide-python` but I guess they are not.

**Comment by ghisvail** [comment]
Support for `pipenv` would be very nice indeed.

**Comment by lucacorti** [comment]
@ghisvail for the record, if you start atom with `pipenv run atom .` in your project dir, `ide-python` will pickup the `venv`. This means you can install `pyls` in pipenv dev-dependencies.

For some reason, this works in one of my setups, but not in another 🤔

**Comment by lgeiger** [comment]
This has been fixed in #150
