### ISSUE TITLE
autoformat doesn't seem to work at all

### ISSUE THREAD

**Issue by mlangiu** [lgeiger/ide-python#129]
Neither <kbd>ctrl</kbd> + <kbd>shift</kbd>+ <kbd>c</kbd> nor format on save works.

OS: Windows 10
Atom    : 1.28.1
Electron: 2.0.4
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by lgeiger** [comment]
Which version of `pyls` are you using and which formatter is enabled in the settings?

**Comment by lgeiger** [comment]
Great that it's working now. Currently IDE packages don't support separate files, but there is a PR open on https://github.com/atom/atom-languageclient trying to change that.
