### ISSUE TITLE
Multiple files open in edited state

### ISSUE THREAD

**Issue by willingc** [lgeiger/ide-python#13]
Hi @lgeiger,

I don't know if this a config thing on my end, but when I open Atom with the Python IDE. It opens a bunch of files that I haven't clicked on. Lots of blue dots ;-)

<img width="1028" alt="screenshot 2017-09-17 20 10 08" src="https://user-images.githubusercontent.com/2680980/30528099-79eda282-9be4-11e7-8eae-8e87c5aaf04f.png">

**Comment by stavinsky** [comment]
Hi. If you open folder, not single file, atom remember what files did you open in past. Just close once, close atom and open that folder again. Everything should be fine

**Comment by lgeiger** [comment]
> Hi. If you open folder, not single file, atom remember what files did you open in past. Just close once, close atom and open that folder again. Everything should be fine

I've made the same observation.
@willingc What happens if you close the unsaved files and restart Atom?

**Comment by willingc** [comment]
Nope. Didn't solve it when I tried the other day. In fact, I likely need to reinstall Atom because the behavior is still around :(

**Comment by lgeiger** [comment]
Which Atom version are you using?

**Comment by willingc** [comment]
1.20.1

**Comment by lgeiger** [comment]
> 1.20.1

You might want to try Atom 1.21.0-beta1

In the [blog post](http://blog.atom.io/2017/09/12/announcing-atom-ide.html) the Atom team mentions:
>We strongly recommended you use **Atom Beta 1.21** as it includes the necessary file monitoring and process control to ensure the underlying language servers are running properly.

**Comment by willingc** [comment]
Ah... Thanks for the tip @lgeiger

**Comment by lgeiger** [comment]
@willingc Atom 1.21 is now stable, is this still a issue?

**Comment by willingc** [comment]
Thanks for the ping. Working well now @lgeiger. Thanks! Closing.
