### ISSUE TITLE
pycodestyle linter gets E712 wrong for Pandas series

### ISSUE THREAD

**Issue by idanrichman** [lgeiger/ide-python#138]
for the following code to check which pandas series values are `False`: 
`df['columnA'] == False`
the linter raises a E712 warning: "comparison to False should be 'if cond is False:' or 'if not cond:'
whereas writing `df['columnA'] is False` will return an entirely different result (of whether the Series object itself is a False)

**Comment by lgeiger** [comment]
This is an issue with `pycodestyle` itself. Please reopen the issue there: https://github.com/PyCQA/pycodestyle

In the meantime you can permanently ignore this error by adding `E712` to the list of ignored PyCodeStyle errors in the IDE-Python settings.
