### ISSUE TITLE
Difference between flake8 messages and inline messages with ide-python

### ISSUE THREAD

**Issue by adammenges** [lgeiger/ide-python#139]
If I run flake8 on the command line, for any given file in a project I see several useful warnings:

``` bash
flake8 --config='setup.cfg' backend/src/graph/graph.py
...
```

But in atom I only see a small subset of them, but there are some, so something is working. Not much config with the plugin I can really change, but I've tried just about every combination of setting that make sense. The config file is called `setup.cfg` which according to the docs means it should be picked up. For what it's worth that flake8 config file from above looks like:

```
[flake8]
ignore =
  D203,
  W191,
  E501,
  E402,
  C901,
  E266
exclude =
  .git,
  __pycache__,
  build,
  dist
max-complexity = 10

```

Presumably there's something obvious I'm missing.

**Comment by lgeiger** [comment]
`ide-python` uses `pyflakes` and `pycodestyle` to lint the code. While it pickes up the flake8 config it only recognises errors supported `pyflakes` and `pycodestyle`. There is a open issue on the Python Lanugage Server repo to add full support for `flake8`.

**Comment by adammenges** [comment]
Okay cool, thanks
