### ISSUE TITLE
Autocomplete on dot

### ISSUE THREAD

**Issue by dpwrussell** [lgeiger/ide-python#16]
Just trying out this IDE and it's great so far, but one thing I noticed was that upon writing, for example `re.` the only autocompletion is a useless one from autocomplete plus:

![screen shot 2017-09-22 at 15 11 03](https://user-images.githubusercontent.com/1889043/30760490-579fe5b0-9fa8-11e7-87bc-8a6d3c06a823.png)

As soon as I enter any more characters it works as expected:

![screen shot 2017-09-22 at 15 11 24](https://user-images.githubusercontent.com/1889043/30760511-715aec02-9fa8-11e7-8866-0ed05fcdc63a.png)

It would be great to get the `ide-python` dot completions at that point like in the Java one:

![screen shot 2017-09-22 at 15 21 11](https://user-images.githubusercontent.com/1889043/30760812-b0d2a504-9fa9-11e7-9eca-8bec5272ff16.png)

Thanks!

**Comment by lgeiger** [comment]
Just published `v0.2.1` with a fix for it.

**Comment by dpwrussell** [comment]
Record broken for speedy fixing!

**Comment by dpwrussell** [comment]
Autocomplete plus still puts the useless one first of course! https://github.com/atom/autocomplete-plus/issues/767. Your upgrade works perfectly though.

**Comment by lgeiger** [comment]
> Autocomplete plus still puts the useless one first of course!

That's a issue with `atom-languageclient`. I submitted a PR to fix this: https://github.com/atom/atom-languageclient/pull/111

Technically we could fix it inside `ide-python` but a I think a upstream fix is better.

**Comment by dpwrussell** [comment]
Agreed, but I also think it would be great to let the user configure their priority in autocomplete plus!
