### ISSUE TITLE
W503 is listed as ignored yet pycodestyle complains

### ISSUE THREAD

**Issue by memeplex** [lgeiger/ide-python#170]
Just that, the setting seems to have no effect at all. I'm in atom 1.37 with the latest version of ide-python. I reported W503, but probably this is a more general issue.

**Comment by memeplex** [comment]
Ah, I think this is because project setup.cfg overrides user configuration. Probably that's the right thing to do, so I'm closing this.

**Comment by rettenbs** [comment]
@memeplex I put the `ignore = W503` everywhere, still atom complains about the code lines. Are you able to ignore this error somehow?
