### ISSUE TITLE
Pylint default max line length set to 100

### ISSUE THREAD

**Issue by hermidalc** [lgeiger/ide-python#175]
I cannot seem to find where ide-python's pylint has a max line length configured to 100

Everywhere in my Atom install core and package configs the max line length is set to the defaults (so 80 or 79 depending on package)

**Comment by hermidalc** [comment]
Ok sorry figured it out, for some reason pylint's default (which is out of line with pep8 and other python line length standards of 79 or 80)

https://github.com/PyCQA/pylint/blob/0eeb67749b6aa016db61d87e55a1f7a7e459b352/pylintrc#L142

**Comment by omarandlorraine** [comment]
Why has this issue been closed? Shouldn't pylint be in line with the peps?
