### ISSUE TITLE
Segmentation fault in atom after installing atom-ide-ui and ide-python

### ISSUE THREAD

**Issue by dchatterjee172** [lgeiger/ide-python#18]
I have installed atom-ide-ui and ide-python

### Description

After opening a file through terminal like,
$ atom test.py
Firstly it takes a lot of time to open, after a window opens, the window becomes unresponsive and i have to force close it, after force closing, this message comes in the terminal,
/usr/bin/atom: line 129: 3930 Segmentation fault (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1

### Versions

Atom: 1.20.1
Client OS: Fedora 26
atom-ide-ui: 0.4.0
ide-python: 0.1.1

### Screenshots
https://www.imageupload.co.uk/image/DNWw
https://www.imageupload.co.uk/image/DNWG
https://www.imageupload.co.uk/image/DNWI

**Comment by lgeiger** [comment]
You might want to try Atom 1.21.0-beta

In the [blog post](http://blog.atom.io/2017/09/12/announcing-atom-ide.html) the Atom team mentions:
>We strongly recommended you use **Atom Beta 1.21** as it includes the necessary file monitoring and process control to ensure the underlying language servers are running properly.

**Comment by dchatterjee172** [comment]
@lgeiger 
same result when using atom beta 1.21
https://hastebin.com/raw/adaguroqay
this are the some new error, i faced multiple exceptions. Cpu usage is 100%. And when I'm force closing it, this message is coming in the terminal 
 /usr/bin/atom-beta: line 129: 26030 Killed                  nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1

**Comment by dchatterjee172** [comment]
@lgeiger I can help you debugging this. Although I have python language server installed, still if ide-python extension is enabled and I try to open any python file, Atom crashes.

**Comment by dchatterjee172** [comment]
After installing the current version of ide-python, the issue seems like resolved

**Comment by lgeiger** [comment]
Glad it's working now.
