### ISSUE TITLE
Type hints are marked as invalid syntax with Pyflakes

### ISSUE THREAD

**Issue by pauzzz** [lgeiger/ide-python#183]
![image](https://user-images.githubusercontent.com/37964863/67724433-57444700-f9b5-11e9-8207-27c385f8dad9.png)

Basically what the title says. I'm on version 1.5 of ide-python. I don't know if this issue happened in previous versions.

**Comment by lgeiger** [comment]
I cannot reproduce this with `pyflakes==2.1.1` (check `pip freeze | grep pyflakes` for your version) and Python 3.7.
Please make sure to run the language server using Python 3, otherwise type hints will be invalid syntax.

**Comment by pauzzz** [comment]
Lol I'm an idiot. Changed the python executable to `python3` and it works fine.
