### ISSUE TITLE
Jedi broken on MacOS

### ISSUE THREAD

**Issue by Xiaohong-Deng** [lgeiger/ide-python#202]
- Platform: MacOS Catalina
- Atom Version: 1.47.0
- Other plugins: MagicPython and [atom community ide](https://atom-ide-community.github.io/), this is a fresh installation with `~/.atom` deleted before installing. No plugins for other languages.
- Describe the bug: autocomplete and hovering to show docstring don't work on non-standard packages like `scipy` and `numpy`. If switch to Rope, autocomplete works.

This plugin works on Ubuntu 18.04. Also `autocomplete-python` works with Jedi on MacOS. Rope works in this plugin. It's just Jedi that does not work on non-standard packages. For packages like `sys` or `os` Jedi works fine.

PS: I installed and removed Kite due to `autocomplete-python`. It's an invaisive software. Not sure if it has anything to do with this problem in `ide-python`

![截屏2020-05-24 上午8 36 52](https://user-images.githubusercontent.com/3221403/82743168-0bfee500-9d9a-11ea-9f7f-2a623b72272f.png)
![截屏2020-05-24 上午8 37 47](https://user-images.githubusercontent.com/3221403/82743169-10c39900-9d9a-11ea-9cdc-e19afc6eac29.png)
![截屏2020-05-24 上午8 38 28](https://user-images.githubusercontent.com/3221403/82743170-1325f300-9d9a-11ea-9384-99ad2aea5cfb.png)
![截屏2020-05-24 上午8 45 05](https://user-images.githubusercontent.com/3221403/82743216-e6261000-9d9a-11ea-8cd1-4f092364560e.png)

**Comment by lgeiger** [comment]
Which version of jedi and python-language-server are you using?

I am currently running `jedi==0.17.0` and `python-language-server==0.32.0` on macOS and autocomplete seems to work fine.

**Comment by Xiaohong-Deng** [comment]
> Which version of jedi and python-language-server are you using?
> 
> I am currently running `jedi==0.17.0` and `python-language-server==0.32.0` on macOS and autocomplete seems to work fine.

Exactly the same versions throught a conda env. So something was messed up so badly even a fresh installation can't fix it.

**Comment by Xiaohong-Deng** [comment]
FWIW, I resolved this issue by falling back to `python-language-server==0.29.1` and `jedi=0.15.1` which are the versions I used on Ubuntu. The problem persists even on a factory reset machine.
