### ISSUE TITLE
atom-ide-community compatibility and some features not working

### ISSUE THREAD

**Issue by Ron-SK** [lgeiger/ide-python#205]

**Comment by lgeiger** [comment]
Yes. I am using it with `atom-ide-community` myself.

@Ron-SK Would you be interested in sending a PR to update the documentation to point users to https://atom-ide-community.github.io/ instead?

**Comment by Ron-SK** [comment]
> Yes. I am using it with `atom-ide-community` myself.
> 
> @Ron-SK Would you be interested in sending a PR to update the documentation to point users to https://atom-ide-community.github.io/ instead?

@lgeiger Sure. I will try to send a PR ASAP. I don't believe some features work such as formatting (hence I am using atom-beautify which is great as well) and I'm not sure whether that's a bug in this package or the `atom-ide-community` set of packages. Additionally, Jedi hover doesn't work on all functions (only a few such as the `print` function). Could you confirm that everything works on your end as you mentioned that you are using this with `atom-ide-community`?

**Comment by Ron-SK** [comment]
Can confirm that I submitted a PR for the documentation to be updated.

**Comment by lgeiger** [comment]
> I don't believe some features work such as formatting

Yes, `atom-ide-community` doesn't provide a mechanism to do code formatting yet.

> Could you confirm that everything works on your end as you mentioned that you are using this with atom-ide-community

For me everything seems to work fine.

> Final question - Is there a way to enable Jedi autocomplete without having to press Ctrl + Space

I think there should be a setting for this in `autocomplete-plus` (I am getting completions on every keystroke).

**Comment by Ron-SK** [comment]
> > I don't believe some features work such as formatting
> 
> Yes, `atom-ide-community` doesn't provide a mechanism to do code formatting yet.
> 
> > Could you confirm that everything works on your end as you mentioned that you are using this with atom-ide-community
> 
> For me everything seems to work fine.
> 
> > Final question - Is there a way to enable Jedi autocomplete without having to press Ctrl + Space
> 
> I think there should be a setting for this in `autocomplete-plus` (I am getting completions on every keystroke).

Oh so I'm supposed to use `ide-python` in tandem with `autocomplete-plus`?

**Comment by lgeiger** [comment]
> Oh so I'm supposed to use ide-python in tandem with autocomplete-plus?

Yes, `ide-python` is a provider for `autocomplete-plus`

**Comment by Ron-SK** [comment]
> > Oh so I'm supposed to use ide-python in tandem with autocomplete-plus?
> 
> Yes, `ide-python` is a provider for `autocomplete-plus`

Thank you so much! I didn't see that in the documentation (README.md) so I was confused.

**Comment by Ron-SK** [comment]
@lgeiger Final things before I close this issue, what are the functions/keywords/etc. that Jedi hover is supposed to work on and is Goto definition enabled? Thank you very much for the support.

**Comment by Ron-SK** [comment]
Can confirm that goto-definition works, not sure about Jedi hover. Closing this issue.
