### ISSUE TITLE
running latest version of atom, still getting error message

### ISSUE THREAD

**Issue by jamesbeedy** [lgeiger/ide-python#24]
<img width="660" alt="screen shot 2017-09-29 at 9 46 44 am" src="https://user-images.githubusercontent.com/5590546/31026431-4417bf88-a4fb-11e7-867f-b72a35293639.png">

It seems I am not eligible for the latest releases even though I'm running the latest atom ....

**Comment by lgeiger** [comment]
`ide-python` targets Atom 1.21+ which is currently still in beta. Checkout this blog post for more information: http://blog.atom.io/2017/09/12/announcing-atom-ide.html

Unfortunately I published 0.1.1 without any Atom version requirements so you were able to install it on Atom 1.20 as well. Sorry for the confusion.

**Comment by lgeiger** [comment]
Atom 1.21 is now stable, so we can close this.
