### ISSUE TITLE
Adding Conventions Support

### ISSUE THREAD

**Issue by SShehriyar** [lgeiger/ide-python#30]
How about adding an info box of some sort that shows the correct convention e.g. Class name should be CamelCase or function names be separated by underscores etc? I guess it can be done using Google Python Style Guide/PEP 8.

**Comment by lgeiger** [comment]
We are using the [python language server](https://github.com/palantir/python-language-server) which as far as I know doesn't support conventions for casing.
Please open a issue on the [language server repo](https://github.com/palantir/python-language-server).

**Comment by SShehriyar** [comment]
Thank you for guiding. Will do :smile:
