### ISSUE TITLE
Unable to start pyls unless started from command line

### ISSUE THREAD

**Issue by simon123h** [lgeiger/ide-python#31]
I am running Atom 1.21.1 on Debian.
I only have python-language-server locally installed via `pip install --user python-language-server`.
pyls is in my path, the command `pyls --version` gives me the desired output.

pyls and python-ide work just fine, when I start Atom from command line. If I do otherwise, eg. by clicking on a file, I get the prompt

> Unable to start the Python language server.
> This can occur if you do not have Python installed or if it is not in your path.
> [...]

I checked the source and there is this line in `main.js:32`:
`// For some reason Atom only detects the correct env if started from the command line on Mac.`
And then some exceptional behavior for Mac.

I feel like I run into the same issue as this comment suggest for Mac. Is that an upstream issue of Atom not detecting the correct env? Should we have a workaround for Debian as well?

**Comment by lgeiger** [comment]
@simon123h Could you try again with `v0.2.3`?

This should now work properly on all operating systems.

**Comment by simon123h** [comment]
Works properly on my machine! Bravo!

**Comment by lgeiger** [comment]
Great!
