### ISSUE TITLE
How can I activate autocomplement?

### ISSUE THREAD

**Issue by Omouu** [lgeiger/ide-python#36]
I remember there were jedi config option once more, but now there is only Python Language Server path setting.

**Comment by exploide** [comment]
Using the current version of ide-python, I still see the config options on the package's settings page. Maybe you need to expand the plugin settings section using the icon on the side?

If you haven't disabled jedi in the past, it should be activated by default. (Beside that, the latest version of palantir/language-server-python also includes autocomplete suggestions from rope. There is no option yet, but should also be enabled by default.)

**Comment by Omouu** [comment]
I did disabled jedi in the past, but now I update ide_python to the newest, jedi changed enabled, autocomplete still not work. I installed autocomplete_python, still not work.

**Comment by Omouu** [comment]
Now I finally fix it. Just uninstalled Atom, and delete everything related to Atom, then reinstalled it.
