### ISSUE TITLE
Python2 and Python3 Linter support? Am I doing this wrong?

### ISSUE THREAD

**Issue by zwolfe21** [lgeiger/ide-python#39]
I might be going about this the wrong way, but sometimes I edit both python2 and python3. Now, this ends up being a problem with pyflakes linter messages. I found a work around but it seems like I might have missed something, must be an easier way, if not, suggestion I suppose!

I install **both** language server packages

`pip install python-language-server --user`
`pip3 install python-language-server --user`

All I gotta do to get Atom, or rather pyflakes from Atom to use either one is edit the first line in ~/.local/bin/pyls to point to either /usr/bin/python2 or /usr/bin/python3.

With that, I have both syntax support. I feel like I gotta be making that more complicated? 

![screenshot from 2017-11-06 17-22-52](https://user-images.githubusercontent.com/24982704/32467162-a23cb3c2-c317-11e7-94b1-0e5d4e5cf586.png)
![screenshot from 2017-11-06 17-22-23](https://user-images.githubusercontent.com/24982704/32467163-a411ff40-c317-11e7-95d8-95ed54de2866.png)

PS: I Use Fedora

**Comment by lgeiger** [comment]
You may want to try the new virtualenv support intruduced in #38.

**Comment by lgeiger** [comment]
`pyls` now allows to be run with the `-m` flag: https://github.com/palantir/python-language-server/pull/344

I think we should switch to this mechanism so people can easily switch between Python versions using a config setting. Though this may be a breaking change for some people since we would need to change the way we start the language server.

**Comment by lgeiger** [comment]
Checkout the release notes of [version 1.0](https://github.com/lgeiger/ide-python/releases/tag/v1.0.0)
