### ISSUE TITLE
python-language-server in a container

### ISSUE THREAD

**Issue by bhack** [lgeiger/ide-python#48]
How we can support the case when we are developing in a container, so python third party modules and the language-server are inside a container?

**Comment by bhack** [comment]
See also https://github.com/atom/atom/issues/14860

**Comment by lgeiger** [comment]
Is there a command that can be used by to start `pyls` inside the container?
If so we could add a config setting to enable executing fully custom command.

Are you interested in experimenting with this and sending a PR? [This is the line](https://github.com/lgeiger/ide-python/blob/master/lib/main.js#L76) to look at for a custom `pyls` command.

**Comment by bhack** [comment]
I meant more something like https://github.com/Glavin001/executables.js/issues/1

**Comment by bhack** [comment]
Take a look to https://github.com/Microsoft/vscode-python/issues/79

**Comment by ibnesayeed** [comment]
It is [ide-ruby](https://atom.io/packages/ide-ruby)'s default behavior. Some ideas can be taken from there to support both on host and in container servers.
