### ISSUE TITLE
Unfriendly fork at jeffhongxiao/ide-python

### ISSUE THREAD

**Issue by ghisvail** [lgeiger/ide-python#49]
Just to let you know of the existence of this rather unfriendly [fork](https://github.com/jeffhongxiao/ide-python) of ide-python, published as [`ide-python-dev`](https://atom.io/packages/ide-python-dev), and whose sole contribution is a renaming of the package and change of version numbering. Besides, the issue tracker has been voluntarily disabled.

**Comment by lgeiger** [comment]
@ghisvail Thanks for the hint.
I wouldn't call this fork unfriendly since `ide-python` is licensed under MIT which grants publishing of copies of the software.
That said @jeffhongxiao is there a specific reason behind your fork?
I'd be happy to join forces and collaborate in order to improve the language server support for python.

**Comment by jeffhongxiao** [comment]
@lgeiger sorry for the confusion. 
i will remove the package on atom if it causes any trouble. 
the only reason for the renaming is i was trying to develop in my local environment.

btw is there any document i can refer to for local development?

**Comment by Arcanemagus** [comment]
@jeffhongxiao Atom's [Flight Manual](http://flight-manual.atom.io/) is the only documentation on how to develop packages, in addition to the [Atom API](https://atom.io/docs/api/latest/AtomEnvironment).

The `tl;dr` is to check out a local copy, run `apm install` to install all the dependencies, run `apm --dev link` to create a link of the package source in your Atom profile's development packages. Then run `atom --dev` to launch Atom in developer mode to load your custom version. If you want your custom version to _always_ run, leave off `--dev` from the commands.
