### ISSUE TITLE
No outline available

### ISSUE THREAD

**Issue by jolsen71** [lgeiger/ide-python#5]
My setup: On Windows 10. Just upgraded to Atom 1.21.0-beta0 and installed atom-ide-ui 0.3.1 and ide-python 0.1.1 packages and the pyls dependency via pip. When I execute "pyls --help" in a command window I get the excepted help text from pyls. 

When I open a .py file in Atom and display the "Outline View" pane, it says "No outline available / There are no outline providers registered"

According to the readme.md for ide-python, the outline view should be a supported feature so I don't know what is preventing it from working on my system. I'm not sure how to troubleshoot this to provide better details to you for debugging/fixing. If there is anything I can run to get you better information please let me know.

Thank you for your time and effort creating ide-python and sharing it with us.

**Comment by lgeiger** [comment]
Are other features like Autocomplete working?

**Comment by lgeiger** [comment]
For me, language servers only start up when I have a project directory with relevant files added to the tree view. You may want to try if this helps.

**Comment by jolsen71** [comment]
I ashamedly do not know for 100% certain, but as I explore I am inclined to say they are not. I tried "find references" and I got a "symbol references are not available for this project"

The linter and diagnostic panes show columns but no content relative to the open file(s)

I will try your suggestion and reply shortly.

**Comment by jolsen71** [comment]
That appears to be the case for me as well; adding a project folder with python files in the path made the outline view, diagnostics view, and other things start working. So, the originally observed issue appears to be with the underlying project--do you happen to know which one (ie Atom-ide-ui)? I will report an issue to them for files edited outside of a project directory.

If you confirm that is the case, then this issue can obviously be closed out as moot and I would recommend adding a note to your readme (that the files being edited need to be in a project folder before the functionality is enabled) to prevent other people reporting this issue to you until the underlying project is fixed up.

Thank you again for your time and fast responses.

**Comment by lgeiger** [comment]
I'm glad it's working for you 🎉 

> So, the originally observed issue appears to be with the underlying project--do you happen to know which one (ie Atom-ide-ui)?

I'm quite new to language-servers so I'm not 100% sure. Either [`atom-language-client`](https://github.com/atom/atom-languageclient) or [`atom-ide-ui`](https://github.com/facebook-atom/atom-ide-ui) should be a good place to ask.

> If you confirm that is the case, then this issue can obviously be closed out as moot and I would recommend adding a note to your readme (that the files being edited need to be in a project folder before the functionality is enabled) to prevent other people reporting this issue to you until the underlying project is fixed up.

👍 Would you like to make a PR and add this note?

> Thank you again for your time and fast responses.

No problem. It's great to see that it works on Windows (I've only tested it on Unix).
Feel free to report any strange behaviors or hickups. [`ide-php`](https://github.com/atom/ide-php/blob/master/lib/main.js#L26) suggests that on Windows it's better to connect to the server via a Socket, but I'm unable to test. Any help is highly appreciated.

**Comment by memeplex** [comment]
> We only fire up the language server if the file you open is contained within the folder you have added to atom.

https://github.com/atom/atom-languageclient/issues/170#issuecomment-358464629
