### ISSUE TITLE
Set version of pyflakes used?

### ISSUE THREAD

**Issue by serramilli** [lgeiger/ide-python#51]
I have both Python 2 and Python 3 installed and pyflakes installed for both. However, since Python 2 is installed as python and Python 3 is installed as python3.6, pyflakes gives syntax errors based on Python 2 syntax. How can I change it so that it uses the Python 3 syntax?

Thanks in advance.

**Comment by lgeiger** [comment]
To use Python 2 and 3 side by side I think you'll need to use virtual envs as introduced in #38.

Otherwise Atom will use the binary which was installed last.

**Comment by lgeiger** [comment]
Please reopen if you still need help.
