### ISSUE TITLE
"pyls --help" can't verify the python-language-server

### ISSUE THREAD

**Issue by imrahul81** [lgeiger/ide-python#52]
I installed the ide-python and python language server using 
`pip install python-language-server`
but running the command
`pyls --help`
gives command not found error.

**Comment by kbatbouta** [comment]
what os are you using because you need to set python bin path

**Comment by luketainton** [comment]
I made sure I installed the package system-wide by using 'sudo' before the command. It worked for me then.

**Comment by lgeiger** [comment]
@kbatbouta @luketainton Thanks for helping!

Closing as resolved/stale.
