### ISSUE TITLE
delaying infoboxes while typing?

### ISSUE THREAD

**Issue by bkroll** [lgeiger/ide-python#54]
is it possible to set a delay between typing and infoboxes appearing, possibly in miliseconds? 

Currently, all infoboxes appear and disappear right away while typing which can be disturbing, especcially while writing comments. A setting to have infoboxes appear only with a short delay after the last key pressed would be great.

**Comment by lgeiger** [comment]
The UI of `ide-python` is controlled by the `atom-ide-ui` package. In the setting of the `atom-ide-ui` package you should find the relevant option.

**Comment by lgeiger** [comment]
Have you tried the suggested solution? Feel free to reopen if it's not working.
