### ISSUE TITLE
Unable to start the Python language server.

### ISSUE THREAD

**Issue by nrfaikar** [lgeiger/ide-python#64]
![screenshot from 2018-01-07 12-18-15](https://user-images.githubusercontent.com/26834955/34646827-e4566d8a-f3a4-11e7-8875-5eeb5ea954fc.png)

How can I get pyls package?

I got some errors "pip install python-language-server":

Collecting python-language-server
  Downloading python-language-server-0.12.1.tar.gz (48kB)
    100% |████████████████████████████████| 51kB 919kB/s 
Collecting configparser (from python-language-server)
  Downloading configparser-3.5.0.tar.gz
Collecting future>=0.14.0 (from python-language-server)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 158kB/s 
Collecting jedi>=0.10 (from python-language-server)
  Downloading jedi-0.11.1-py2.py3-none-any.whl (250kB)
    100% |████████████████████████████████| 256kB 279kB/s 
Collecting json-rpc (from python-language-server)
  Downloading json_rpc-1.10.8-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 876kB/s 
Collecting mccabe (from python-language-server)
  Downloading mccabe-0.6.1-py2.py3-none-any.whl
Collecting pycodestyle (from python-language-server)
  Downloading pycodestyle-2.3.1-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 444kB/s 
Collecting pydocstyle (from python-language-server)
  Downloading pydocstyle-2.1.1-py2-none-any.whl
Collecting pyflakes (from python-language-server)
  Downloading pyflakes-1.6.0-py2.py3-none-any.whl (227kB)
    100% |████████████████████████████████| 235kB 14kB/s 
Collecting rope>=0.10.5 (from python-language-server)
  Downloading rope-0.10.7.tar.gz (244kB)
    100% |████████████████████████████████| 245kB 249kB/s 
Collecting yapf (from python-language-server)
  Downloading yapf-0.20.0-py2.py3-none-any.whl (158kB)
    100% |████████████████████████████████| 163kB 483kB/s 
Collecting pluggy (from python-language-server)
  Downloading pluggy-0.6.0.tar.gz
Requirement already satisfied: parso==0.1.1 in /usr/lib64/python2.7/site-packages (from jedi>=0.10->python-language-server)
Requirement already satisfied: six in /usr/lib64/python2.7/site-packages (from pydocstyle->python-language-server)
Requirement already satisfied: snowballstemmer in /usr/lib64/python2.7/site-packages (from pydocstyle->python-language-server)
Installing collected packages: configparser, future, jedi, json-rpc, mccabe, pycodestyle, pydocstyle, pyflakes, rope, yapf, pluggy, python-language-server
  Running setup.py install for configparser ... error
    Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wDL4K0/configparser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-KQH9ku-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying src/configparser.py -> build/lib
    creating build/lib/backports
    copying src/backports/__init__.py -> build/lib/backports
    creating build/lib/backports/configparser
    copying src/backports/configparser/helpers.py -> build/lib/backports/configparser
    copying src/backports/configparser/__init__.py -> build/lib/backports/configparser
    running egg_info
    writing src/configparser.egg-info/PKG-INFO
    writing namespace_packages to src/configparser.egg-info/namespace_packages.txt
    writing top-level names to src/configparser.egg-info/top_level.txt
    writing dependency_links to src/configparser.egg-info/dependency_links.txt
    reading manifest file 'src/configparser.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'src/configparser.egg-info/SOURCES.txt'
    running install_lib
    copying configparser.py -> /usr/lib/python2.7/site-packages
    error: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/configparser.py'
    
    ----------------------------------------
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wDL4K0/configparser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-KQH9ku-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-wDL4K0/configparser/

**Comment by nrfaikar** [comment]
Sorry, my fault

**Comment by samarth-math** [comment]
Seeing the same error:
whereis pyls
pyls: /usr/local/bin/pyls
-- this is part of PATH

I see the following error in atom : Error: spawn pyls ENOENT
