### ISSUE TITLE
pyls absolute path doesn't expand

### ISSUE THREAD

**Issue by horjulf** [lgeiger/ide-python#65]
The absolute path to pyls doesn't expand when using home aliases or environment variables.

Works:
`/home/test/.pyenv/shims/pyls`

Doesn't work:
`~/.pyenv/shims/pyls`
`$HOME/.pyenv/shims/pyls`

This breaks config portability, should be an easy fix.
Tested on MacOS 10.13.2 with Atom 1.23.2.

**Comment by lgeiger** [comment]
> This breaks config portability, should be an easy fix.

Want to send a PR to fix this?

**Comment by lgeiger** [comment]
Checkout the release notes of [version 1.0](https://github.com/lgeiger/ide-python/releases/tag/v1.0.0)

**Comment by funkyfuture** [comment]
with Atom 1.44.0 and ide-python 1.5.0, i can't use neither `$HOME` nor `~`, but must specify an absoulte path to the python binary.
