### ISSUE TITLE
Files opened by fuzzy find palette not triggering python language server.

### ISSUE THREAD

**Issue by extraymond** [lgeiger/ide-python#68]
**Environment**
Linux x64 ubuntu 16.04

**Atom version**
1.24.0.beta3, 1.23.1

**Encountered situation**

Greetings, I've encountered a weird behaviour. 

If I open a file from the project file tree, python language server is working properly. 
But if the file is opened by ctrl-p (opens fuzzy file finder), the linter and all the ide stuff is not working.

**Comment by lgeiger** [comment]
AFAIK Atom only starts a language server if the file is part of a project added to the current workspace.

This issue is better filed on the [`atom-langaugeclient`](https://github.com/atom/atom-languageclient) repo since it controls the language server.

**Comment by extraymond** [comment]
Thx for your reply, I will try to open issue on it instead.

Raymond
extraymond@gmail.com (https://link.getmailspring.com/link/local-a12ad8f3-b831@extraymond-desktop/0?redirect=mailto%3Aextraymond%40gmail.com&recipient=reply%2B000aca68786730910d8401bd303a4f17ea68fab367191a1a92cf0000000116734da092a169ce1130f7bc%40reply.github.com)

**Comment by lgeiger** [comment]
Thanks! -> https://github.com/atom/atom-languageclient/issues/170
