### ISSUE TITLE
error installing phyton ide

### ISSUE THREAD

**Issue by hidenName** [lgeiger/ide-python#7]
![erroratom](https://user-images.githubusercontent.com/30762101/30407546-1a4c6196-98cf-11e7-982b-c613aca191a1.PNG)

**Comment by willingc** [comment]
@hidenName Try the following command to install the python language server:
```
python3 -m pip install python-language-server
```

**Comment by lgeiger** [comment]
If the above doesn't solve your issue, try to run the script with system administrators privilege.

Your Python installation may require admin privilege to install packages. Checkout [this tutorial](https://winaero.com/blog/how-to-open-elevated-command-prompt-in-windows-10/) on how to open the command prompt in with elevated privileges.

**Comment by stavinsky** [comment]
I don't know your language, but "acceso denegado"  looks like mean access denied. So @lgeiger 100% right, try to run as administrator or use virtualenv

**Comment by lgeiger** [comment]
@hidenName Did you get it working?

**Comment by lgeiger** [comment]
I'm closing this issue. Feel free to reopen if you still need help.
