### ISSUE TITLE
pyls not recognized in terminal nor working in atom

### ISSUE THREAD

**Issue by SShehriyar** [lgeiger/ide-python#71]
Operating System: Pop OS (Linux)
Atom Version: 1.23.3 x64
pyls version: 0.13.0

I tried adding pyls to the path but on bash it was not recognizing the command. In zsh, it returned an error saying permission denied. I tried adding the path to the ide-python settings in atom i.e. 

    /home/sshehriyar/.local/lib/python3.6/site-packages/pyls

but it is not working (no autocomplete, function info etc). 

If i import pyls from python3 interpreter, it successfully imports it.

This is the error I'm getting in the developer tools console log:

    Uncaught (in promise) Error: spawn EACCES
    at exports._errnoException (util.js:1022)
    at ChildProcess.spawn (internal/child_process.js:313)
    at Object.exports.spawn (child_process.js:399)
    at PythonLanguageClient.startServerProcess (/home/sshehriyar/.atom/packages/ide-python/lib/main.js:76)

**Comment by SShehriyar** [comment]
Alright I fixed it by installing the python-language-server globally using sudo with pip :smile:

**Comment by Evpok** [comment]
That's not very good practice, have you tried adding `/home/sshehriyar/.local/bin` to your `$PATH` instead ?

**Comment by SShehriyar** [comment]
@Evpok oh, was i directing it to the wrong directory? I saw the description saying "path to pyls executable" but I was not sure where the executable was getting installed. I'll try directing the ide-python package to .local/bin/pyls :smile:

**Comment by SShehriyar** [comment]
@Evpok alright i fixed it without installing the language server by root. Thanks!
