### ISSUE TITLE
trouble with python-language-server.......

### ISSUE THREAD

**Issue by afroz1198** [lgeiger/ide-python#72]
# I guess i installed packages from python language server
 `$ pip install python-language-server

Collecting python-language-server
Collecting json-rpc (from python-language-server)
  Using cached json_rpc-1.10.8-py2.py3-none-any.whl
Collecting pydocstyle (from python-language-server)
  Using cached pydocstyle-2.1.1-py2-none-any.whl
Collecting jedi>=0.10 (from python-language-server)
  Using cached jedi-0.11.1-py2.py3-none-any.whl
Collecting mccabe (from python-language-server)
  Using cached mccabe-0.6.1-py2.py3-none-any.whl
Collecting future>=0.14.0 (from python-language-server)
Collecting pluggy (from python-language-server)
Collecting pyflakes (from python-language-server)
  Using cached pyflakes-1.6.0-py2.py3-none-any.whl
Collecting yapf (from python-language-server)
  Using cached yapf-0.20.1-py2.py3-none-any.whl
Collecting pycodestyle (from python-language-server)
  Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Collecting configparser (from python-language-server)
Collecting rope>=0.10.5 (from python-language-server)
Collecting six (from pydocstyle->python-language-server)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting snowballstemmer (from pydocstyle->python-language-server)
  Using cached snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting parso==0.1.1 (from jedi>=0.10->python-language-server)
  Using cached parso-0.1.1-py2.py3-none-any.whl
Installing collected packages: json-rpc, six, configparser, snowballstemmer, pydocstyle, parso, jedi, mccabe, future, pluggy, pyflakes, yapf, pycodestyle, rope, python-language-server
 **Successfully installed configparser-3.5.0 future-0.16.0 jedi-0.11.1 json-rpc-1.10.8 mccabe-0.6.1 parso-0.1.1 pluggy-0.6.0 pycodestyle-2.3.1 pydocstyle-2.1.1 pyflakes-1.6.0 python-language-server-0.13.0 rope-0.10.7 six-1.11.0 snowballstemmer-1.2.1 yapf-0.20.1**`
_but the pyls command is not found_

**Comment by Evpok** [comment]
Check that `$HOME/.local/bin` is in your `PATH`

**Comment by lgeiger** [comment]
@Evpok 👍

Closing as inactive.
