### ISSUE TITLE
Pycodestyle config doesn't work in Windows

### ISSUE THREAD

**Issue by klicperajo** [lgeiger/ide-python#78]
On Windows 10 the global pycodestyle config is saved under ~\\.pycodestyle (i.e. C:\Users\\[username]). I've set up this file and it works when calling pycodestyle directly. However, it does not work in ide-python.
Furthermore, copying the file to ~\\.config\pycodestyle, ~\\.config\\.pycodestyle or ~\pycodestyle doesn't work either (pyls 0.12.2, pycodestyle 2.3.1, ide-python 0.7.0).

~\\.pycodestyle
[pycodestyle]
ignore = E731

**Comment by lgeiger** [comment]
I'm confident that this will be fixed in the next `pyls` release.

**Comment by lgeiger** [comment]
Could you try and upgrade `pyls` to 0.14.0?

**Comment by klicperajo** [comment]
After the upgrade the config works as expected. Thank you! :)
