### ISSUE TITLE
support 'flake8' as a pyls Plugins Configuration Source

### ISSUE THREAD

**Issue by ediphy-azorab** [lgeiger/ide-python#80]
pyls appears to support flake8 as a configuration source. It may well be the case that adding 'flake8' to the set of allowed strings might be sufficient to get this going?

**Comment by lgeiger** [comment]
@ediphy-azorab Want to try it out and send a PR if it works?

**Comment by lgeiger** [comment]
Oh I just looked at the [`pyls` config code](https://github.com/palantir/python-language-server/tree/develop/pyls/config) and I think `pyflakes` should be replaced with `flake8`.

I just copied it from the [vscode extension](https://github.com/palantir/python-language-server/tree/develop/pyls/config) which made the same mistake.

@ediphy-azorab Want to send a PR to fix this?

**Comment by lgeiger** [comment]
Amazing. Keep those PRs coming 🎉
