### ISSUE TITLE
Uncaught Error: Connection is disposed. #63 present with ide-python 0.7.0

### ISSUE THREAD

**Issue by Chistabo** [lgeiger/ide-python#82]
I have un-checked 'PyDocStyle', and this error, which has been reported previously (#63), poped-up.
Using ide-python 0.7.0.
FYI.

Simon

**Comment by alexandernst** [comment]
I'm hitting this every single time I enable or disable any python and IDE related package.

**Comment by lgeiger** [comment]
I was able to finally able to reliably reproduce this.

https://github.com/atom/atom-languageclient/pull/219 will fix this issue.

**Comment by brandonkal** [comment]
I can reproduce this by adding `E501` ti thie list of ignored warnings.

**Comment by lgeiger** [comment]
This should be fixed in version 1.0.1
