### ISSUE TITLE
Persistent Cyclomatic complexity warning

### ISSUE THREAD

**Issue by SShehriyar** [lgeiger/ide-python#83]
I got a warning saying I have 17 parameters and the max limit is 15. I added some of the parameters to a list and passed that list as a parameter to reduce the total number of parameters but I'm still getting the error.I thought the variables inside the list are counted so I removed the parameters to the point so that there are only 3 or 4 left but the warning is still present saying I have 17 parameters. I've attached screenshots below If they are of any help.
![atom_bug](https://user-images.githubusercontent.com/28010024/36073213-80fbd0d4-0f4e-11e8-83d0-31e3cb5b413f.png)
![atom_bug_2](https://user-images.githubusercontent.com/28010024/36073214-8135046c-0f4e-11e8-80a6-49b9c6cc728d.png)

**Comment by exploide** [comment]
Are you sure it is about the parameters? Cyclomatic complexity typically is about the control flow graph of your function. https://en.wikipedia.org/wiki/Cyclomatic_complexity

Maybe your functions contains a huge amount of `if` statements and similar constructs which influence the number of branches in your code.

**Comment by SShehriyar** [comment]
Oh yeah it has nothing to do with the parameters. My bad, should've at least looked what Cyclomatic complexity really meant. Thanks. 😄
