### ISSUE TITLE
pyls initializing for ... forever.

### ISSUE THREAD

**Issue by efaden** [lgeiger/ide-python#85]
Title says it all.  I have OSX with pyenv, virtualenv, and virtualenvwrapper setup.  My current python is 3.6.4 and the pyls is installed and on the path.  When I load up a python file in the editor i see a spinning logo in the bottom corner saying pyls is initializing.  It just never does anything else.  Thoughts?

**Comment by lgeiger** [comment]
Can you provide more information on which versions of `pyls`, `ide-python` and Atom you're using?

**Comment by efaden** [comment]
Which ever the latest ide-python is.  Pyls is python-language-server (0.14.0).  Atom is 1.24.

**Comment by churnikorn** [comment]
Can confirm I've got the same issue, also running on latest of all three

**Comment by lgeiger** [comment]
@efaden @churnikorn Could you enable debug messages by executing `atom.config.set('core.debugLSP', true)` in the Developer Tools Console and post a screenshot of the console output when this issue occurs? You might need to restart Atom in order to see the debug messages.

**Comment by dAnjou** [comment]
Same here on Fedora 27:

- python-language-server 0.15.1 via `pip install --user python-language-server`
- Atom 1.24.0 via Flatpak
- ide-python 0.8.1 via Atom Package Manager

![atom_pyls_error](https://user-images.githubusercontent.com/117147/36908734-660d7532-1e3c-11e8-9e92-23458d51805f.png)

**Comment by lgeiger** [comment]
This looks like `pyls` isn't installed correctly. Judging from the [`pyls` install script](https://github.com/palantir/python-language-server/blob/88712b5fe7208cf508c0467c2596663e78a9f710/versioneer.py#L218-L229) there may be a problem with old versions of `setuptools`.

Could you try to update `setuptools`, reinstall `pyls` and restart Atom?

Depending on your python setup the following commands *should* do the trick:
```bash
pip uninstall python-language-server
pip install setuptools --upgrade
pip install python-language-server
```

**Comment by lgeiger** [comment]
Linking https://github.com/palantir/python-language-server/issues/308 for reference.

**Comment by rocarvaj** [comment]
Hi!
This worked for me. I opened a terminal and executed `pyls --help` to see what happened and I got the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyls", line 7, in <module>
    from pyls.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/pyls/__main__.py", line 7, in <module>
    from .python_ls import start_io_lang_server, start_tcp_lang_server, PythonLanguageServer
  File "/usr/local/lib/python2.7/dist-packages/pyls/python_ls.py", line 6, in <module>
    from .config import config
  File "/usr/local/lib/python2.7/dist-packages/pyls/config/config.py", line 9, in <module>
    from .pycodestyle_conf import PyCodeStyleConfig
  File "/usr/local/lib/python2.7/dist-packages/pyls/config/pycodestyle_conf.py", line 2, in <module>
    import pycodestyle
ImportError: No module named pycodestyle
```
:man_facepalming:
So I went ahead and `pip install pycodestyle` and problem solved!

**Comment by austen0** [comment]
The solution provided by @rocarvaj resolved this issue for me. Thanks!

**Comment by BEFH** [comment]
Didn't work for me.

**Comment by jkw** [comment]
Confirming that @rocarvaj solution worked for me too. Had same symptoms as @efaden but on Linux.

**Comment by mayursss** [comment]
solution given by @rocarvaj worked

**Comment by justinsolms** [comment]
solution given by @rocarvaj worked

**Comment by lgeiger** [comment]
Thanks to all for investigating.

For future readers and judging from the comments this issue can likely be resolved by reinstalling `pls`:
```shell
pip uninstall python-language-server
pip install 'python-language-server[all]' --upgrade
```

**Comment by jasonkuhrt** [comment]
I had this same symptom for a different reason. I had done `pip install python-language-server` on my machine. Then entered a directory with a virtualenv setup. When I booted Atom in this directory it couldn't find the globally installed `pyls` because I had not installed it locally. And there is no error feedback telling you this. Perhaps obvious to experienced Python developers but figured out how these various tools interact is a bit confusing for newcomers (I'm one).

**Comment by joost823** [comment]
I have this issue as well and tried the solutions mentioned here, but nothing worked. I am **not** doing anything in a virtualenv.

Only have one version of python installed (3.6.5). Windows 10 64 bit. Atom 1.30.0, atom-ide-ui 0.13.0 and python-ide 1.0.0. 

Tried reinstalling atom, and removing `.atom` dir. Tried reinstalling all packages. Tried reinstalling pyls. Tried it in another project, but no results.


`pip freeze`:

```
autopep8==1.4
future==0.16.0
jedi==0.12.1
mccabe==0.6.1
parso==0.3.1
pluggy==0.7.1
pycodestyle==2.4.0
pydocstyle==2.1.1
pyflakes==2.0.0
python-jsonrpc-server==0.0.1
python-language-server==0.21.2
rope==0.11.0
six==1.11.0
snowballstemmer==1.2.1
virtualenv==16.0.0
yapf==0.24.0
```

Running `pyls --help` in the command line gives me 
```
usage: pyls [-h] [--tcp] [--host HOST] [--port PORT]
            [--log-config LOG_CONFIG | --log-file LOG_FILE] [-v]

Python Language Server

optional arguments: ...
```

Before updating the atom packages, I had the error: `The Python (pyls) language server has exited and exceeded the restart limit for project`. But that had only 6 (!) results on google, and nothing useful between them either.

So pyls seems to not be the problem. Any ideas?

**Comment by joost823** [comment]
@McKelian This worked for me: https://github.com/lgeiger/ide-python/issues/119#issuecomment-417079777

Remove pyls and all dependencies. The install correct (downgraded) version of pyls and all the dependencies.

**Comment by LeGoffLoic** [comment]
Everything is up to date for me, no error message and no outline ...

**Comment by jkw** [comment]
> 
> 
> @McKelian This worked for me: [#119 (comment)](https://github.com/lgeiger/ide-python/issues/119#issuecomment-417171455)
> 
> Remove pyls and all dependencies. The install correct (downgraded) version of pyls and all the dependencies.

Thank you for this comment, now works flawlessly.

**Comment by Muelsa** [comment]
Hi I hope everyone is well today. I got this error trying to install it.

Using cached https://files.pythonhosted.org/packages/9f/1d/2817b5dc2dd77f897410a11c1c9e2a6d96b3273c53d4219dd9edab7882af/python-language-server-0.21.2.tar.gz
    Complete output from command python setup.py egg_info:
    error in python-language-server setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in configparser; python_version<"3.0" at ; python_version<"3.0"

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jv/n_9v394x73s98jrb3z22ttgr0000gn/T/pip-install-lfYYqk/python-language-server/

Any solution?

**Comment by sp-rky** [comment]
I was using pip3 instead of pip...
If anyone is having this issue try switching to pip instead. It worked for me.

**Comment by anthcor** [comment]
wanted to drop this here because im noticing some weird issues with the latest installation of pyls[all] (0.33.0) when working in a fresh virtualenv 

steps to fix (assuming no custom executable settings in ide-python) ...

```sh
# quit atom 
# from a virtualenv in your workdir
source env/bin/activate
pip uninstall 'python-language-server[all]'
pip install 'python-language-server[all]==0.29.0'
which pyls # make sure it's installed to something like /workdir/env/bin/pyls
# reopen atom from workdir
```

**Comment by zilbert97** [comment]
I had been having this issue and tried everything above (as well as here: https://github.com/lgeiger/ide-python/issues/134). The following worked for me, by updating python on my machine and then updating to the latest pyls at the command line (on Mac):

```
brew update && brew upgrade python  # installed what Homebrew recognises as latest version of python, 3.8.6
brew install pyenv
pyenv install 3.8.6  # or whichever version you've installed
pyenv global 3.8.6
echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bash_profile  # or ~/.zshrc if you're on zsh

echo "alias python=/usr/local/bin/python3" >> ~/.bash_profile 
echo "alias pip=/usr/local/bin/pip3" >> ~/.bash_profile

python -m pip install 'python-language-server[all]'  # this seemed to install/update a whole bunch of dependencies

# Restarted atom
# Disabled and re-enabled ide-python under settings > packages
```

I followed the steps here https://opensource.com/article/19/5/python-3-default-mac because i've never been sure if my initial setup of Python3 was done correctly.

Probably not the best way, especially if you don't want to run Python v3.8.6. Not sure how this worked but not complaining!
