### ISSUE TITLE
All pycodestyle issues disappeared after upgrade

### ISSUE THREAD

**Issue by terrytangyuan** [lgeiger/ide-python#87]
I was on my way fixing some pycodestyle issues and then upgraded my ide-python to the latest 0.8.0. However, all the pycodestyle issues that I was trying to fix disappeared in my code. Is anyone else having this issue? Let me know if you need more information to reproduce this.

**Comment by terrytangyuan** [comment]
@lgeiger I saw you added this commit: https://github.com/lgeiger/ide-python/commit/97cb04bfee25713fa3b3a18b990388ebe7343181

However,  it seems like `select` and `ignore` should be of `string` type instead of `array`? Please correct me if I am wrong since I am not really familiar with `pycodestyle`.

**Comment by lgeiger** [comment]
There was a bug in an earlier version of `python-langiage-server`. Could you update to the latest version and try again?

**Comment by terrytangyuan** [comment]
Thanks. It works now again!
