### ISSUE TITLE
Ignore errors

### ISSUE THREAD

**Issue by AragurDEV** [lgeiger/ide-python#9]
It would be great if there would be an option to filter the errors wich are displayed.
For example E501

**Comment by lgeiger** [comment]
I don't think this is currently possible with [`python-language-server`](https://github.com/palantir/python-language-server).

Though I think [disabling whole plugins](https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json#L22) should work in theory. Would you be interested in implementing this feature and sending a PR?

**Comment by blakegong** [comment]
Do this: https://pycodestyle.readthedocs.io/en/latest/intro.html#configuration

Explanation: [python-language-server](https://github.com/palantir/python-language-server) uses [pycodestyle](https://github.com/PyCQA/pycodestyle), which could be configured globally using 👆 

Still, would love a way to simply pass the message down to `pycodestyle` through `ide-python`. Looking forward to it :D
