### ISSUE TITLE
Pyls will not install

### ISSUE THREAD

**Issue by auralmenace** [lgeiger/ide-python#93]
Hi, thanks for all the hard work!
I can't get pyls to install. In terminal, I get the output pasted below. I do a system-wide sears for pyls but it doesn't exist - so the PATH fix won't help. 
Thanks in Advance!

>> kevintill $ pip install python-language-server
Collecting python-language-server
  Using cached python-language-server-0.15.1.tar.gz
    Complete output from command python setup.py egg_info:
    error in python-language-server setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in futures; python_version == "2.7" at ; python_version == "2.7"

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wm/xf08w4n57fxfljzk12tc751c0000gn/T/pip-build-TGmD8U/python-language-server/

**Comment by lgeiger** [comment]
Could you try upgrading pip and setuptools and try again?

**Comment by auralmenace** [comment]
I was having issues with Python overall - installed python 3 on the command line instead of using python.org's installer (mac OS) using this very handy tutorial: 

http://docs.python-guide.org/en/latest/starting/install3/osx/

I had to backtrack and fix my Ruby and Brew as well to get the Python up and running, and a PATH fix too, but all seems well now.

Thanks for the quick response.

**Comment by lgeiger** [comment]
:+1: Glad it's working now.
